"""Static market-cap universe for automated regulatory filing intake."""

UNIVERSE_SNAPSHOT_DATE = "2026-07-29"
UNIVERSE_SOURCE = "https://companiesmarketcap.com/"
EU_UNIVERSE_SOURCE = "https://www.financecharts.com/screener/biggest-country-europe"

TOP_US_COMPANIES = (
    {"company": "Apple", "symbol": "AAPL", "region": "US", "market": "US", "market_rank": 1, "cik": "0000320193"},
    {"company": "NVIDIA", "symbol": "NVDA", "region": "US", "market": "US", "market_rank": 2, "cik": "0001045810"},
    {"company": "Alphabet (Google)", "symbol": "GOOG", "region": "US", "market": "US", "market_rank": 3, "cik": "0001652044"},
    {"company": "Microsoft", "symbol": "MSFT", "region": "US", "market": "US", "market_rank": 4, "cik": "0000789019"},
    {"company": "Amazon", "symbol": "AMZN", "region": "US", "market": "US", "market_rank": 5, "cik": "0001018724"},
    {"company": "Broadcom", "symbol": "AVGO", "region": "US", "market": "US", "market_rank": 6, "cik": "0001730168"},
    {"company": "SpaceX", "symbol": "SPCX", "region": "US", "market": "US", "market_rank": 7, "cik": "0001181412"},
    {"company": "Meta Platforms (Facebook)", "symbol": "META", "region": "US", "market": "US", "market_rank": 8, "cik": "0001326801"},
    {"company": "Tesla", "symbol": "TSLA", "region": "US", "market": "US", "market_rank": 9, "cik": "0001318605"},
    {"company": "Berkshire Hathaway", "symbol": "BRK-B", "region": "US", "market": "US", "market_rank": 10, "cik": "0001067983"},
    {"company": "Eli Lilly", "symbol": "LLY", "region": "US", "market": "US", "market_rank": 11, "cik": "0000059478"},
    {"company": "JPMorgan Chase", "symbol": "JPM", "region": "US", "market": "US", "market_rank": 12, "cik": "0000019617"},
    {"company": "Micron Technology", "symbol": "MU", "region": "US", "market": "US", "market_rank": 13, "cik": "0000723125"},
    {"company": "Walmart", "symbol": "WMT", "region": "US", "market": "US", "market_rank": 14, "cik": "0000104169"},
    {"company": "AMD", "symbol": "AMD", "region": "US", "market": "US", "market_rank": 15, "cik": "0000002488"},
    {"company": "Visa", "symbol": "V", "region": "US", "market": "US", "market_rank": 16, "cik": "0001403161"},
    {"company": "Johnson & Johnson", "symbol": "JNJ", "region": "US", "market": "US", "market_rank": 17, "cik": "0000200406"},
    {"company": "Exxon Mobil", "symbol": "XOM", "region": "US", "market": "US", "market_rank": 18, "cik": "0002115436"},
    {"company": "Mastercard", "symbol": "MA", "region": "US", "market": "US", "market_rank": 19, "cik": "0001141391"},
    {"company": "AbbVie", "symbol": "ABBV", "region": "US", "market": "US", "market_rank": 20, "cik": "0001551152"},
    {"company": "Cisco", "symbol": "CSCO", "region": "US", "market": "US", "market_rank": 21, "cik": "0000858877"},
    {"company": "Bank of America", "symbol": "BAC", "region": "US", "market": "US", "market_rank": 22, "cik": "0000070858"},
    {"company": "Intel", "symbol": "INTC", "region": "US", "market": "US", "market_rank": 23, "cik": "0000050863"},
    {"company": "Costco", "symbol": "COST", "region": "US", "market": "US", "market_rank": 24, "cik": "0000909832"},
    {"company": "UnitedHealth", "symbol": "UNH", "region": "US", "market": "US", "market_rank": 25, "cik": "0000731766"},
    {"company": "Caterpillar", "symbol": "CAT", "region": "US", "market": "US", "market_rank": 26, "cik": "0000018230"},
    {"company": "Coca-Cola", "symbol": "KO", "region": "US", "market": "US", "market_rank": 27, "cik": "0000021344"},
    {"company": "Applied Materials", "symbol": "AMAT", "region": "US", "market": "US", "market_rank": 28, "cik": "0000006951"},
    {"company": "General Electric", "symbol": "GE", "region": "US", "market": "US", "market_rank": 29, "cik": "0000040545"},
    {"company": "Chevron", "symbol": "CVX", "region": "US", "market": "US", "market_rank": 30, "cik": "0000093410"},
    {"company": "Procter & Gamble", "symbol": "PG", "region": "US", "market": "US", "market_rank": 31, "cik": "0000080424"},
    {"company": "Oracle", "symbol": "ORCL", "region": "US", "market": "US", "market_rank": 32, "cik": "0001341439"},
    {"company": "Home Depot", "symbol": "HD", "region": "US", "market": "US", "market_rank": 33, "cik": "0000354950"},
    {"company": "Lam Research", "symbol": "LRCX", "region": "US", "market": "US", "market_rank": 34, "cik": "0000707549"},
    {"company": "Morgan Stanley", "symbol": "MS", "region": "US", "market": "US", "market_rank": 35, "cik": "0000895421"},
    {"company": "Merck", "symbol": "MRK", "region": "US", "market": "US", "market_rank": 36, "cik": "0000310158"},
    {"company": "Philip Morris International", "symbol": "PM", "region": "US", "market": "US", "market_rank": 37, "cik": "0001413329"},
    {"company": "Goldman Sachs", "symbol": "GS", "region": "US", "market": "US", "market_rank": 38, "cik": "0000886982"},
    {"company": "Netflix", "symbol": "NFLX", "region": "US", "market": "US", "market_rank": 39, "cik": "0001065280"},
    {"company": "Palantir", "symbol": "PLTR", "region": "US", "market": "US", "market_rank": 40, "cik": "0001321655"},
    {"company": "RTX", "symbol": "RTX", "region": "US", "market": "US", "market_rank": 41, "cik": "0000101829"},
    {"company": "Wells Fargo", "symbol": "WFC", "region": "US", "market": "US", "market_rank": 42, "cik": "0000072971"},
    {"company": "Palo Alto Networks", "symbol": "PANW", "region": "US", "market": "US", "market_rank": 43, "cik": "0001327567"},
    {"company": "Dell", "symbol": "DELL", "region": "US", "market": "US", "market_rank": 44, "cik": "0001571996"},
    {"company": "Texas Instruments", "symbol": "TXN", "region": "US", "market": "US", "market_rank": 45, "cik": "0000097476"},
    {"company": "GE Vernova", "symbol": "GEV", "region": "US", "market": "US", "market_rank": 46, "cik": "0001996810"},
    {"company": "KLA", "symbol": "KLAC", "region": "US", "market": "US", "market_rank": 47, "cik": "0000319201"},
    {"company": "American Express", "symbol": "AXP", "region": "US", "market": "US", "market_rank": 48, "cik": "0000004962"},
    {"company": "Citigroup", "symbol": "C", "region": "US", "market": "US", "market_rank": 49, "cik": "0000831001"},
    {"company": "IBM", "symbol": "IBM", "region": "US", "market": "US", "market_rank": 50, "cik": "0000051143"},
    {"company": "Thermo Fisher Scientific", "symbol": "TMO", "region": "US", "market": "US", "market_rank": 51, "cik": "0000097745"},
    {"company": "Arista Networks", "symbol": "ANET", "region": "US", "market": "US", "market_rank": 52, "cik": "0001596532"},
    {"company": "Amgen", "symbol": "AMGN", "region": "US", "market": "US", "market_rank": 53, "cik": "0000318154"},
    {"company": "Verizon", "symbol": "VZ", "region": "US", "market": "US", "market_rank": 54, "cik": "0000732712"},
    {"company": "T-Mobile US", "symbol": "TMUS", "region": "US", "market": "US", "market_rank": 55, "cik": "0001283699"},
    {"company": "Pepsico", "symbol": "PEP", "region": "US", "market": "US", "market_rank": 56, "cik": "0000077476"},
    {"company": "McDonald", "symbol": "MCD", "region": "US", "market": "US", "market_rank": 57, "cik": "0000063908"},
    {"company": "Abbott Laboratories", "symbol": "ABT", "region": "US", "market": "US", "market_rank": 58, "cik": "0000001800"},
    {"company": "Nextera Energy", "symbol": "NEE", "region": "US", "market": "US", "market_rank": 59, "cik": "0000753308"},
    {"company": "CrowdStrike", "symbol": "CRWD", "region": "US", "market": "US", "market_rank": 60, "cik": "0001535527"},
    {"company": "Charles Schwab", "symbol": "SCHW", "region": "US", "market": "US", "market_rank": 61, "cik": "0000316709"},
    {"company": "BlackRock", "symbol": "BLK", "region": "US", "market": "US", "market_rank": 62, "cik": "0002012383"},
    {"company": "Analog Devices", "symbol": "ADI", "region": "US", "market": "US", "market_rank": 63, "cik": "0000006281"},
    {"company": "TJX Companies", "symbol": "TJX", "region": "US", "market": "US", "market_rank": 64, "cik": "0000109198"},
    {"company": "Amphenol", "symbol": "APH", "region": "US", "market": "US", "market_rank": 65, "cik": "0000820313"},
    {"company": "Welltower", "symbol": "WELL", "region": "US", "market": "US", "market_rank": 66, "cik": "0000766704"},
    {"company": "Boeing", "symbol": "BA", "region": "US", "market": "US", "market_rank": 67, "cik": "0000012927"},
    {"company": "Union Pacific Corporation", "symbol": "UNP", "region": "US", "market": "US", "market_rank": 68, "cik": "0000100885"},
    {"company": "Deere & Company (John Deere)", "symbol": "DE", "region": "US", "market": "US", "market_rank": 69, "cik": "0000315189"},
    {"company": "Walt Disney", "symbol": "DIS", "region": "US", "market": "US", "market_rank": 70, "cik": "0001744489"},
    {"company": "QUALCOMM", "symbol": "QCOM", "region": "US", "market": "US", "market_rank": 71, "cik": "0000804328"},
    {"company": "AT&T", "symbol": "T", "region": "US", "market": "US", "market_rank": 72, "cik": "0000732717"},
    {"company": "Gilead Sciences", "symbol": "GILD", "region": "US", "market": "US", "market_rank": 73, "cik": "0000882095"},
    {"company": "Blackstone Group", "symbol": "BX", "region": "US", "market": "US", "market_rank": 74, "cik": "0001393818"},
    {"company": "Sandisk", "symbol": "SNDK", "region": "US", "market": "US", "market_rank": 75, "cik": "0002023554"},
    {"company": "Western Digital", "symbol": "WDC", "region": "US", "market": "US", "market_rank": 76, "cik": "0000106040"},
    {"company": "Marvell Technology", "symbol": "MRVL", "region": "US", "market": "US", "market_rank": 77, "cik": "0001835632"},
    {"company": "Booking Holdings (Booking.com)", "symbol": "BKNG", "region": "US", "market": "US", "market_rank": 78, "cik": "0001075531"},
    {"company": "Interactive Brokers", "symbol": "IBKR", "region": "US", "market": "US", "market_rank": 79, "cik": "0001381197"},
    {"company": "Salesforce", "symbol": "CRM", "region": "US", "market": "US", "market_rank": 80, "cik": "0001108524"},
    {"company": "Uber", "symbol": "UBER", "region": "US", "market": "US", "market_rank": 81, "cik": "0001543151"},
    {"company": "Pfizer", "symbol": "PFE", "region": "US", "market": "US", "market_rank": 82, "cik": "0000078003"},
    {"company": "AppLovin", "symbol": "APP", "region": "US", "market": "US", "market_rank": 83, "cik": "0001751008"},
    {"company": "Prologis", "symbol": "PLD", "region": "US", "market": "US", "market_rank": 84, "cik": "0001045609"},
    {"company": "Southern Copper", "symbol": "SCCO", "region": "US", "market": "US", "market_rank": 85, "cik": "0001001838"},
    {"company": "Danaher", "symbol": "DHR", "region": "US", "market": "US", "market_rank": 86, "cik": "0000313616"},
    {"company": "CVS Health", "symbol": "CVS", "region": "US", "market": "US", "market_rank": 87, "cik": "0000064803"},
    {"company": "ConocoPhillips", "symbol": "COP", "region": "US", "market": "US", "market_rank": 88, "cik": "0001163165"},
    {"company": "Lockheed Martin", "symbol": "LMT", "region": "US", "market": "US", "market_rank": 89, "cik": "0000936468"},
    {"company": "Stryker Corporation", "symbol": "SYK", "region": "US", "market": "US", "market_rank": 90, "cik": "0000310764"},
    {"company": "Capital One", "symbol": "COF", "region": "US", "market": "US", "market_rank": 91, "cik": "0000927628"},
    {"company": "Bristol-Myers Squibb", "symbol": "BMY", "region": "US", "market": "US", "market_rank": 92, "cik": "0000014272"},
    {"company": "Intuitive Surgical", "symbol": "ISRG", "region": "US", "market": "US", "market_rank": 93, "cik": "0001035267"},
    {"company": "Progressive", "symbol": "PGR", "region": "US", "market": "US", "market_rank": 94, "cik": "0000080661"},
    {"company": "S&P Global", "symbol": "SPGI", "region": "US", "market": "US", "market_rank": 95, "cik": "0000064040"},
    {"company": "Parker-Hannifin", "symbol": "PH", "region": "US", "market": "US", "market_rank": 96, "cik": "0000076334"},
    {"company": "Altria Group", "symbol": "MO", "region": "US", "market": "US", "market_rank": 97, "cik": "0000764180"},
    {"company": "Vertex Pharmaceuticals", "symbol": "VRTX", "region": "US", "market": "US", "market_rank": 98, "cik": "0000875320"},
    {"company": "Lowe's Companies", "symbol": "LOW", "region": "US", "market": "US", "market_rank": 99, "cik": "0000060667"},
    {"company": "Starbucks", "symbol": "SBUX", "region": "US", "market": "US", "market_rank": 100, "cik": "0000829224"},
)

TOP_UK_COMPANIES = (
    {"company": "HSBC", "symbol": "HSBC", "region": "EU", "market": "UK", "market_rank": 1, "company_number": "00617987", "cik": "0001089113"},
    {"company": "AstraZeneca", "symbol": "AZN", "region": "EU", "market": "UK", "market_rank": 2, "company_number": "02723534", "cik": "0000901832"},
    {"company": "Arm Holdings", "symbol": "ARM", "region": "EU", "market": "UK", "market_rank": 3, "company_number": "11299879", "cik": "0001973239"},
    {"company": "Shell", "symbol": "SHEL", "region": "EU", "market": "UK", "market_rank": 4, "company_number": "04366849", "cik": "0001306965"},
    {"company": "Linde", "symbol": "LIN", "region": "EU", "market": "UK", "market_rank": 5, "company_number": "FC039973", "cik": "0001707925"},
    {"company": "Rolls-Royce Holdings", "symbol": "RR.L", "region": "EU", "market": "UK", "market_rank": 6, "company_number": "07524813"},
    {"company": "Rio Tinto", "symbol": "RIO", "region": "EU", "market": "UK", "market_rank": 7, "company_number": "00719885", "cik": "0000863064"},
    {"company": "Unilever", "symbol": "UL", "region": "EU", "market": "UK", "market_rank": 8, "company_number": "00041424", "cik": "0000217410"},
    {"company": "British American Tobacco", "symbol": "BTI", "region": "EU", "market": "UK", "market_rank": 9, "company_number": "03407696", "cik": "0001303523"},
    {"company": "GSK plc", "symbol": "GSK", "region": "EU", "market": "UK", "market_rank": 10, "company_number": "03888792", "cik": "0001131399"},
    {"company": "BP", "symbol": "BP", "region": "EU", "market": "UK", "market_rank": 11, "company_number": "00102498", "cik": "0000313807"},
    {"company": "Barclays", "symbol": "BCS", "region": "EU", "market": "UK", "market_rank": 12, "company_number": "00048839", "cik": "0000312069"},
    {"company": "Lloyds Banking Group", "symbol": "LYG", "region": "EU", "market": "UK", "market_rank": 13, "company_number": "SC095000", "cik": "0001160106"},
    {"company": "Aon", "symbol": "AON", "region": "EU", "market": "UK", "market_rank": 14, "cik": "0000315293"},
    {"company": "National Grid", "symbol": "NGG", "region": "EU", "market": "UK", "market_rank": 15, "company_number": "04031152", "cik": "0001004315"},
    {"company": "BAE Systems", "symbol": "BA.L", "region": "EU", "market": "UK", "market_rank": 16, "company_number": "01470151"},
    {"company": "NatWest Group", "symbol": "NWG", "region": "EU", "market": "UK", "market_rank": 17, "company_number": "SC045551", "cik": "0000844150"},
    {"company": "RELX", "symbol": "RELX", "region": "EU", "market": "UK", "market_rank": 18, "company_number": "00077536", "cik": "0000929869"},
    {"company": "Standard Chartered", "symbol": "STAN.L", "region": "EU", "market": "UK", "market_rank": 19, "company_number": "00966425"},
    {"company": "London Stock Exchange", "symbol": "LSEG.L", "region": "EU", "market": "UK", "market_rank": 20, "company_number": "05369106"},
    {"company": "Compass Group", "symbol": "CPG.L", "region": "EU", "market": "UK", "market_rank": 21, "company_number": "04083914"},
    {"company": "Anglo American", "symbol": "AAL.L", "region": "EU", "market": "UK", "market_rank": 22, "company_number": "03564138"},
    {"company": "Diageo", "symbol": "DEO", "region": "EU", "market": "UK", "market_rank": 23, "company_number": "00023307", "cik": "0000835403"},
    {"company": "Coca-Cola European Partners", "symbol": "CCEP", "region": "EU", "market": "UK", "market_rank": 24, "company_number": "09717350", "cik": "0001650107"},
    {"company": "Antofagasta", "symbol": "ANTO.L", "region": "EU", "market": "UK", "market_rank": 25, "company_number": "01627889"},
    {"company": "Haleon", "symbol": "HLN", "region": "EU", "market": "UK", "market_rank": 26, "company_number": "13691224", "cik": "0001900304"},
    {"company": "Ferguson Enterprises", "symbol": "FERG", "region": "EU", "market": "UK", "market_rank": 27, "cik": "0002011641"},
    {"company": "Reckitt Benckiser", "symbol": "RKT.L", "region": "EU", "market": "UK", "market_rank": 28, "company_number": "06270876"},
    {"company": "Tesco", "symbol": "TSCO.L", "region": "EU", "market": "UK", "market_rank": 29, "company_number": "00445790"},
    {"company": "3i Group", "symbol": "III.L", "region": "EU", "market": "UK", "market_rank": 30, "company_number": "01142830"},
    {"company": "Vodafone", "symbol": "VOD", "region": "EU", "market": "UK", "market_rank": 31, "company_number": "01833679", "cik": "0000839923"},
    {"company": "SSE", "symbol": "SSE.L", "region": "EU", "market": "UK", "market_rank": 32, "company_number": "SC117119"},
    {"company": "Prudential", "symbol": "PUK", "region": "EU", "market": "UK", "market_rank": 33, "company_number": "01397169", "cik": "0001116578"},
    {"company": "Royalty Pharma", "symbol": "RPRX", "region": "EU", "market": "UK", "market_rank": 34, "company_number": "12446913", "cik": "0001802768"},
    {"company": "Ashtead", "symbol": "AHT.L", "region": "EU", "market": "UK", "market_rank": 35, "company_number": "01807982"},
    {"company": "Willis Towers Watson", "symbol": "WTW", "region": "EU", "market": "UK", "market_rank": 36, "company_number": "FC035970", "cik": "0001140536"},
    {"company": "Imperial Brands", "symbol": "IMB.L", "region": "EU", "market": "UK", "market_rank": 37, "company_number": "03236483"},
    {"company": "TechnipFMC", "symbol": "FTI", "region": "EU", "market": "UK", "market_rank": 38, "company_number": "09909709", "cik": "0001681459"},
    {"company": "Aviva", "symbol": "AV.L", "region": "EU", "market": "UK", "market_rank": 39, "company_number": "02468686"},
    {"company": "BT Group", "symbol": "BT-A.L", "region": "EU", "market": "UK", "market_rank": 40, "company_number": "04190816"},
    {"company": "Roivant Sciences", "symbol": "ROIV", "region": "EU", "market": "UK", "market_rank": 41, "company_number": "FC039660", "cik": "0001635088"},
    {"company": "InterContinental Hotels Group", "symbol": "IHG", "region": "EU", "market": "UK", "market_rank": 42, "company_number": "05134420", "cik": "0000858446"},
    {"company": "Next plc", "symbol": "NXT.L", "region": "EU", "market": "UK", "market_rank": 43, "company_number": "04412362"},
    {"company": "nVent Electric", "symbol": "NVT", "region": "EU", "market": "UK", "market_rank": 44, "company_number": "FC034686", "cik": "0001720635"},
    {"company": "Legal & General", "symbol": "LGEN.L", "region": "EU", "market": "UK", "market_rank": 45, "company_number": "01417162"},
    {"company": "Associated British Foods", "symbol": "ABF.L", "region": "EU", "market": "UK", "market_rank": 46, "company_number": "00293262"},
    {"company": "SEGRO", "symbol": "SGRO.L", "region": "EU", "market": "UK", "market_rank": 47, "company_number": "00167591"},
    {"company": "Halma", "symbol": "HLMA.L", "region": "EU", "market": "UK", "market_rank": 48, "company_number": "00040932"},
    {"company": "Airtel Africa", "symbol": "AAF.L", "region": "EU", "market": "UK", "market_rank": 49, "company_number": "11462215"},
    {"company": "Informa plc", "symbol": "INF.L", "region": "EU", "market": "UK", "market_rank": 50, "company_number": "08860726"},
    {"company": "Admiral Group", "symbol": "ADM.L", "region": "EU", "market": "UK", "market_rank": 51, "company_number": "03849958"},
    {"company": "Rentokil Initial", "symbol": "RTO", "region": "EU", "market": "UK", "market_rank": 52, "company_number": "05393279", "cik": "0000930157"},
    {"company": "CNH Industrial", "symbol": "CNH", "region": "EU", "market": "UK", "market_rank": 53, "company_number": "FC031116", "cik": "0001567094"},
    {"company": "Smith & Nephew", "symbol": "SNN", "region": "EU", "market": "UK", "market_rank": 54, "company_number": "00324357", "cik": "0000845982"},
    {"company": "United Utilities", "symbol": "UU.L", "region": "EU", "market": "UK", "market_rank": 55, "company_number": "02366616"},
    {"company": "Diploma plc", "symbol": "DPLM.L", "region": "EU", "market": "UK", "market_rank": 56, "company_number": "03899848"},
    {"company": "Schroders", "symbol": "SDR.L", "region": "EU", "market": "UK", "market_rank": 57, "company_number": "03909886"},
    {"company": "Severn Trent", "symbol": "SVT.L", "region": "EU", "market": "UK", "market_rank": 58, "company_number": "02366619"},
    {"company": "Bunzl", "symbol": "BNZL.L", "region": "EU", "market": "UK", "market_rank": 59, "company_number": "00358948"},
    {"company": "Intertek", "symbol": "ITRK.L", "region": "EU", "market": "UK", "market_rank": 60, "company_number": "04267576"},
    {"company": "Wise PLC", "symbol": "WISE.L", "region": "EU", "market": "UK", "market_rank": 61, "company_number": "13211214"},
    {"company": "Sage Group", "symbol": "SGE.L", "region": "EU", "market": "UK", "market_rank": 62, "company_number": "02231246"},
    {"company": "Endeavour Mining", "symbol": "EDV.TO", "region": "EU", "market": "UK", "market_rank": 63, "company_number": "13280545"},
    {"company": "M&G plc", "symbol": "MNG.L", "region": "EU", "market": "UK", "market_rank": 64, "company_number": "11444019"},
    {"company": "Marks & Spencer", "symbol": "MKS.L", "region": "EU", "market": "UK", "market_rank": 65, "company_number": "04256886"},
    {"company": "Pentair", "symbol": "PNR", "region": "EU", "market": "UK", "market_rank": 66, "company_number": "FC034739", "cik": "0000077360"},
    {"company": "Pearson", "symbol": "PSO", "region": "EU", "market": "UK", "market_rank": 67, "company_number": "00053723", "cik": "0000938323"},
    {"company": "Phoenix Group", "symbol": "PHNX.L", "region": "EU", "market": "UK", "market_rank": 68, "company_number": "11606773"},
    {"company": "Smiths Group", "symbol": "SMIN.L", "region": "EU", "market": "UK", "market_rank": 69, "company_number": "00137013"},
    {"company": "Sainsbury's", "symbol": "SBRY.L", "region": "EU", "market": "UK", "market_rank": 70, "company_number": "00185647"},
    {"company": "Beazley", "symbol": "BEZ.L", "region": "EU", "market": "UK", "market_rank": 71, "company_number": "09763575"},
    {"company": "Summit Therapeutics", "symbol": "SMMT", "region": "EU", "market": "UK", "market_rank": 72, "company_number": "05197494", "cik": "0001599298"},
    {"company": "Centrica", "symbol": "CNA.L", "region": "EU", "market": "UK", "market_rank": 73, "company_number": "03033654"},
    {"company": "The Weir Group", "symbol": "WEIR.L", "region": "EU", "market": "UK", "market_rank": 74, "company_number": "SC002934"},
    {"company": "IMI plc", "symbol": "IMI.L", "region": "EU", "market": "UK", "market_rank": 75, "company_number": "00714275"},
    {"company": "Games Workshop Group", "symbol": "GAW.L", "region": "EU", "market": "UK", "market_rank": 76, "company_number": "02670969"},
    {"company": "Janus Henderson", "symbol": "JHG", "region": "EU", "market": "UK", "market_rank": 77, "company_number": "FC031677"},
    {"company": "Investec", "symbol": "INVR.L", "region": "EU", "market": "UK", "market_rank": 78, "company_number": "03633621"},
    {"company": "Melrose Industries", "symbol": "MRO.L", "region": "EU", "market": "UK", "market_rank": 79, "company_number": "09800044"},
    {"company": "Babcock International Group", "symbol": "BAB.L", "region": "EU", "market": "UK", "market_rank": 80, "company_number": "02342138"},
    {"company": "IG Group", "symbol": "IGG.L", "region": "EU", "market": "UK", "market_rank": 81, "company_number": "04677092"},
    {"company": "Intermediate Capital Group (ICG)", "symbol": "ICG.L", "region": "EU", "market": "UK", "market_rank": 82, "company_number": "02234775"},
    {"company": "St. James's Place", "symbol": "STJ.L", "region": "EU", "market": "UK", "market_rank": 83, "company_number": "03183415"},
    {"company": "Land Securities Group", "symbol": "LAND.L", "region": "EU", "market": "UK", "market_rank": 84, "company_number": "04369054"},
    {"company": "Spirax-Sarco Engineering", "symbol": "SPX.L", "region": "EU", "market": "UK", "market_rank": 85, "company_number": "00596337"},
    {"company": "Computacenter", "symbol": "CCC.L", "region": "EU", "market": "UK", "market_rank": 86, "company_number": "03110569"},
    {"company": "Kingfisher", "symbol": "KGF.L", "region": "EU", "market": "UK", "market_rank": 87, "company_number": "01664812"},
    {"company": "Pepco Group", "symbol": "PCO.WA", "region": "EU", "market": "UK", "market_rank": 88, "company_number": "09127609"},
    {"company": "Lion Finance Group PLC", "symbol": "BGEO.L", "region": "EU", "market": "UK", "market_rank": 89, "company_number": "10917019"},
    {"company": "Centessa Pharmaceuticals", "symbol": "CNTA", "region": "EU", "market": "UK", "market_rank": 90, "company_number": "12973576"},
    {"company": "Noble Corporation", "symbol": "NE", "region": "EU", "market": "UK", "market_rank": 91, "company_number": "12958050", "cik": "0001895262"},
    {"company": "Tritax Big Box REIT", "symbol": "BBOX.L", "region": "EU", "market": "UK", "market_rank": 92, "company_number": "08215888"},
    {"company": "LondonMetric Property", "symbol": "LMP.L", "region": "EU", "market": "UK", "market_rank": 93, "company_number": "07124797"},
    {"company": "easyJet", "symbol": "EZJ.L", "region": "EU", "market": "UK", "market_rank": 94, "company_number": "03959649"},
    {"company": "JD Sports Fashion", "symbol": "JD.L", "region": "EU", "market": "UK", "market_rank": 95, "company_number": "01888425"},
    {"company": "British Land", "symbol": "BLND.L", "region": "EU", "market": "UK", "market_rank": 96, "company_number": "00621920"},
    {"company": "Croda International", "symbol": "CRDA.L", "region": "EU", "market": "UK", "market_rank": 97, "company_number": "00206132"},
    {"company": "Convatec Group", "symbol": "CTEC.L", "region": "EU", "market": "UK", "market_rank": 98, "company_number": "10361298"},
    {"company": "Howden Joinery", "symbol": "HWDN.L", "region": "EU", "market": "UK", "market_rank": 99, "company_number": "02128710"},
    {"company": "Whitbread", "symbol": "WTB.L", "region": "EU", "market": "UK", "market_rank": 100, "company_number": "04120344"},
)

TOP_EU_COMPANIES = (
    {"company": "ASML Holding", "symbol": "ASML", "region": "EU", "market": "EU", "market_rank": 1, "country": "NL", "industry": "Information Technology", "lei": "724500Y6DUVHQD6OXN27", "cik": "0000937966"},
    {"company": "LVMH Moet Hennessy Louis Vuitton", "symbol": "LVMUY", "region": "EU", "market": "EU", "market_rank": 2, "country": "FR", "industry": "Consumer Discretionary", "lei": "IOG4E947OATN0KJYSD45"},
    {"company": "Siemens", "symbol": "SIEGY", "region": "EU", "market": "EU", "market_rank": 3, "country": "DE", "industry": "Industrials", "lei": "529900VGZ27M5ZHAEZ97"},
    {"company": "L'Oreal", "symbol": "LRLCY", "region": "EU", "market": "EU", "market_rank": 4, "country": "FR", "industry": "Consumer Staples", "lei": "529900JI1GG6F7RKVI53"},
    {"company": "Novo Nordisk", "symbol": "NVO", "region": "EU", "market": "EU", "market_rank": 5, "country": "DK", "industry": "Health Care", "lei": "894500G05T7MXFP5E425", "cik": "0000353278"},
    {"company": "Novozymes", "symbol": "NVZMY", "region": "EU", "market": "EU", "market_rank": 6, "country": "DK", "industry": "Materials", "lei": "529900T6WNZXD2R3JW38"},
    {"company": "SAP", "symbol": "SAP", "region": "EU", "market": "EU", "market_rank": 7, "country": "DE", "industry": "Information Technology", "lei": "894500AZV132AEWQR576", "cik": "0001000184"},
    {"company": "Banco Santander", "symbol": "SAN", "region": "EU", "market": "EU", "market_rank": 8, "country": "ES", "industry": "Financials", "lei": "959800YEZQBZNN7WVG77", "cik": "0000891478"},
    {"company": "Hermes International SCA", "symbol": "HESAY", "region": "EU", "market": "EU", "market_rank": 9, "country": "FR", "industry": "Consumer Discretionary", "lei": "969500Y4IJGHJE2MTJ13"},
    {"company": "Industria de Diseno Textil", "symbol": "IDEXY", "region": "EU", "market": "EU", "market_rank": 10, "country": "ES", "industry": "Consumer Discretionary", "lei": "549300TTCXZOGZM2EY83"},
    {"company": "Airbus", "symbol": "EADSY", "region": "EU", "market": "EU", "market_rank": 11, "country": "NL", "industry": "Industrials", "lei": "MINO79WLOO247M1IL051"},
    {"company": "Allianz", "symbol": "ALIZY", "region": "EU", "market": "EU", "market_rank": 12, "country": "DE", "industry": "Financials", "lei": "529900K9B0N5BT694847"},
    {"company": "Schneider Electric", "symbol": "SBGSY", "region": "EU", "market": "EU", "market_rank": 13, "country": "FR", "industry": "Industrials", "lei": "969500A1YF1XUYYXS284"},
    {"company": "TotalEnergies", "symbol": "TTE", "region": "EU", "market": "EU", "market_rank": 14, "country": "FR", "industry": "Energy", "lei": "529900S21EQ1BO4ESM68", "cik": "0000879764"},
    {"company": "Safran", "symbol": "SAFRY", "region": "EU", "market": "EU", "market_rank": 15, "country": "FR", "industry": "Industrials", "lei": "969500U91C71UJI8WR10"},
    {"company": "Iberdrola", "symbol": "IBDRY", "region": "EU", "market": "EU", "market_rank": 16, "country": "ES", "industry": "Utilities", "lei": "5QK37QC7NWOJ8D7WVQ45"},
    {"company": "Deutsche Telekom", "symbol": "DTEGY", "region": "EU", "market": "EU", "market_rank": 17, "country": "DE", "industry": "Communication Services", "lei": "391200FLQDJPMF09I019", "cik": "0000946770"},
    {"company": "Banco Bilbao Vizcaya Argentaria", "symbol": "BBVA", "region": "EU", "market": "EU", "market_rank": 18, "country": "ES", "industry": "Financials", "lei": "K8MS7FD7N5Z2WQ51AZ71", "cik": "0000842180"},
    {"company": "Siemens Energy", "symbol": "SMEGF", "region": "EU", "market": "EU", "market_rank": 19, "country": "DE", "industry": "Industrials", "cik": "0001830056"},
    {"company": "UniCredit SpA", "symbol": "UNCRY", "region": "EU", "market": "EU", "market_rank": 20, "country": "IT", "industry": "Financials"},
    {"company": "BNP Paribas", "symbol": "BNPQY", "region": "EU", "market": "EU", "market_rank": 21, "country": "FR", "industry": "Financials", "lei": "R0MUWSFPU8MPRO8K5P83"},
    {"company": "Intesa Sanpaolo", "symbol": "ISNPY", "region": "EU", "market": "EU", "market_rank": 22, "country": "IT", "industry": "Financials", "lei": "213800ALUI5LNBGGXM45"},
    {"company": "Air Liquide", "symbol": "AIQUY", "region": "EU", "market": "EU", "market_rank": 23, "country": "FR", "industry": "Materials", "lei": "969500MMPQVHK671GT54"},
    {"company": "Investor", "symbol": "IVSBF", "region": "EU", "market": "EU", "market_rank": 24, "country": "SE", "industry": "Financials", "lei": "549300VEBQPHRZBKUX38"},
    {"company": "Spotify Technology", "symbol": "SPOT", "region": "EU", "market": "EU", "market_rank": 25, "country": "LU", "industry": "Communication Services", "lei": "549300B4X0JHWV0DTD60", "cik": "0001639920"},
    {"company": "Enel SpA", "symbol": "ENLAY", "region": "EU", "market": "EU", "market_rank": 26, "country": "IT", "industry": "Utilities", "lei": "WOCMU6HCI0OJWNPRZS33"},
    {"company": "Genmab", "symbol": "GMAB", "region": "EU", "market": "EU", "market_rank": 27, "country": "DK", "industry": "Health Care", "lei": "529900MTJPDPE4MHJ122", "cik": "0001434265"},
    {"company": "Prada SpA", "symbol": "PRDSY", "region": "EU", "market": "EU", "market_rank": 28, "country": "IT", "industry": "Consumer Discretionary"},
    {"company": "Sanofi", "symbol": "SNY", "region": "EU", "market": "EU", "market_rank": 29, "country": "FR", "industry": "Health Care", "lei": "549300E9PC51EN656011", "cik": "0001121404"},
    {"company": "AXA", "symbol": "AXAHY", "region": "EU", "market": "EU", "market_rank": 30, "country": "FR", "industry": "Financials", "lei": "F5WCUMTUM4RKZ1MAIE39"},
    {"company": "CaixaBank", "symbol": "CAIXY", "region": "EU", "market": "EU", "market_rank": 31, "country": "ES", "industry": "Financials", "lei": "7CUNS533WID6K7DGFI87"},
    {"company": "Atlas Copco", "symbol": "ATLCY", "region": "EU", "market": "EU", "market_rank": 32, "country": "SE", "industry": "Industrials", "lei": "549300KNUX62XP1WXM21"},
    {"company": "ING Groep", "symbol": "ING", "region": "EU", "market": "EU", "market_rank": 33, "country": "NL", "industry": "Financials", "lei": "549300NYKK9MWM7GGW15", "cik": "0001039765"},
    {"company": "Infineon Technologies", "symbol": "IFNNY", "region": "EU", "market": "EU", "market_rank": 34, "country": "DE", "industry": "Information Technology", "lei": "52990032QYE86GO8SK75", "cik": "0001107457"},
    {"company": "Christian Dior", "symbol": "CHDRY", "region": "EU", "market": "EU", "market_rank": 35, "country": "FR", "industry": "Consumer Discretionary", "lei": "969500WESYQMQ1F2C272"},
    {"company": "Essilorluxottica", "symbol": "ESLOY", "region": "EU", "market": "EU", "market_rank": 36, "country": "FR", "industry": "Health Care", "lei": "549300M3VH1A3ER1TB49"},
    {"company": "Engie", "symbol": "ENGIY", "region": "EU", "market": "EU", "market_rank": 37, "country": "FR", "industry": "Utilities", "lei": "549300ZDNPE0178O3T39"},
    {"company": "Ferrari", "symbol": "RACE", "region": "EU", "market": "EU", "market_rank": 38, "country": "IT", "industry": "Consumer Discretionary", "lei": "894500D5B6A8E1W0VQ35", "cik": "0001648416"},
    {"company": "Assicurazioni Generali", "symbol": "ARZGY", "region": "EU", "market": "EU", "market_rank": 39, "country": "IT", "industry": "Financials", "lei": "549300X5UKJVE386ZB61"},
    {"company": "Vinci", "symbol": "VCISY", "region": "EU", "market": "EU", "market_rank": 40, "country": "FR", "industry": "Industrials"},
    {"company": "Prosus", "symbol": "PROSY", "region": "EU", "market": "EU", "market_rank": 41, "country": "NL", "industry": "Consumer Discretionary", "lei": "254900L5YI0BCU0KKA17"},
    {"company": "Muenchener Rueckversicherungs Gesellschaft", "symbol": "MURGY", "region": "EU", "market": "EU", "market_rank": 42, "country": "DE", "industry": "Financials"},
    {"company": "Volvo", "symbol": "VLVLY", "region": "EU", "market": "EU", "market_rank": 43, "country": "SE", "industry": "Industrials", "lei": "549300P5JZ7GDEJQ8R74"},
    {"company": "Eni SpA", "symbol": "E", "region": "EU", "market": "EU", "market_rank": 44, "country": "IT", "industry": "Energy", "cik": "0001002242"},
    {"company": "Deutsche Post", "symbol": "DHLGY", "region": "EU", "market": "EU", "market_rank": 45, "country": "DE", "industry": "Industrials", "lei": "391200NE04DA1X1S2B28"},
    {"company": "Merck KGaA", "symbol": "MKKGY", "region": "EU", "market": "EU", "market_rank": 46, "country": "DE", "industry": "Health Care", "lei": "5299005OWNZ0MY5ODB36"},
    {"company": "Deutsche Bank", "symbol": "DB", "region": "EU", "market": "EU", "market_rank": 47, "country": "DE", "industry": "Financials", "lei": "3912007KGGUR8HY25C94", "cik": "0001159508"},
    {"company": "Credit Agricole", "symbol": "CRARY", "region": "EU", "market": "EU", "market_rank": 48, "country": "FR", "industry": "Financials", "lei": "969500SRQKP7167VWF70"},
    {"company": "NXP Semiconductors", "symbol": "NXPI", "region": "EU", "market": "EU", "market_rank": 49, "country": "NL", "industry": "Information Technology", "lei": "724500M9BY5293JDF951", "cik": "0001413447"},
    {"company": "Societe Generale", "symbol": "SCGLY", "region": "EU", "market": "EU", "market_rank": 50, "country": "FR", "industry": "Financials", "lei": "O2RNE8IBXP4R0TD8PU41"},
    {"company": "Thales", "symbol": "THLLY", "region": "EU", "market": "EU", "market_rank": 51, "country": "FR", "industry": "Industrials", "lei": "894500BH3UL1SBV81H04"},
    {"company": "E.ON", "symbol": "EONGY", "region": "EU", "market": "EU", "market_rank": 52, "country": "DE", "industry": "Utilities", "lei": "5493003UAA28MK6MYY62", "cik": "0001136808"},
    {"company": "Rheinmetall", "symbol": "RNMBY", "region": "EU", "market": "EU", "market_rank": 53, "country": "DE", "industry": "Industrials", "lei": "5299001OU9CSE29O6S05"},
    {"company": "Erste Group Bank", "symbol": "EBKDY", "region": "EU", "market": "EU", "market_rank": 54, "country": "AT", "industry": "Financials", "lei": "PQOH26KWDF7CG10L6792"},
    {"company": "Deutsche Boerse", "symbol": "DBOEY", "region": "EU", "market": "EU", "market_rank": 55, "country": "DE", "industry": "Financials"},
    {"company": "Nkt", "symbol": "NRKBY", "region": "EU", "market": "EU", "market_rank": 56, "country": "DK", "industry": "Industrials", "lei": "549300L41EGP6YNKSD31"},
    {"company": "Bayer", "symbol": "BAYRY", "region": "EU", "market": "EU", "market_rank": 57, "country": "DE", "industry": "Health Care", "lei": "529900775ZURFY5PNH71"},
    {"company": "Danone", "symbol": "DANOY", "region": "EU", "market": "EU", "market_rank": 58, "country": "FR", "industry": "Consumer Staples", "lei": "9695001EBYSERQNW7D97"},
    {"company": "RWE", "symbol": "RWEOY", "region": "EU", "market": "EU", "market_rank": 59, "country": "DE", "industry": "Utilities", "lei": "529900TVPTSXBKCVDA80"},
    {"company": "DSV", "symbol": "DSDVY", "region": "EU", "market": "EU", "market_rank": 60, "country": "DK", "industry": "Industrials", "lei": "5493000CWUBIYEUD9611"},
    {"company": "Orange", "symbol": "ORANY", "region": "EU", "market": "EU", "market_rank": 61, "country": "FR", "industry": "Communication Services", "lei": "969500MCOONR8990S771", "cik": "0001038143"},
    {"company": "Mercedes Benz Group", "symbol": "MBGYY", "region": "EU", "market": "EU", "market_rank": 62, "country": "DE", "industry": "Consumer Discretionary", "lei": "529900R27DL06UVNT076"},
    {"company": "BASF", "symbol": "BASFY", "region": "EU", "market": "EU", "market_rank": 63, "country": "DE", "industry": "Materials", "lei": "391200QTZL8BLISOWV09"},
    {"company": "argenx", "symbol": "ARGX", "region": "EU", "market": "EU", "market_rank": 64, "country": "NL", "industry": "Health Care", "lei": "7245009C5FZE6G9ODQ71", "cik": "0001697862"},
    {"company": "Nokia Oyj", "symbol": "NOK", "region": "EU", "market": "EU", "market_rank": 65, "country": "FI", "industry": "Information Technology", "lei": "549300A0JPRWG1KI7U06", "cik": "0000924613"},
    {"company": "Heineken", "symbol": "HEINY", "region": "EU", "market": "EU", "market_rank": 66, "country": "NL", "industry": "Consumer Staples", "lei": "724500K5PTPSST86UQ23"},
    {"company": "Commerzbank", "symbol": "CRZBY", "region": "EU", "market": "EU", "market_rank": 67, "country": "DE", "industry": "Financials", "lei": "391200G80JWX8TZAWD59"},
    {"company": "Endesa", "symbol": "ELEZY", "region": "EU", "market": "EU", "market_rank": 68, "country": "ES", "industry": "Utilities", "lei": "549300O1SC78BDUF3J58"},
    {"company": "Rockwool", "symbol": "RCWLY", "region": "EU", "market": "EU", "market_rank": 69, "country": "DK", "industry": "Industrials", "lei": "549300NWKGD5AZC6NG55", "cik": "0001969729"},
    {"company": "Aena SME", "symbol": "ANYYY", "region": "EU", "market": "EU", "market_rank": 70, "country": "ES", "industry": "Industrials", "lei": "959800R7QMXKF0NFMT29"},
    {"company": "Sandvik", "symbol": "SDVKY", "region": "EU", "market": "EU", "market_rank": 71, "country": "SE", "industry": "Industrials", "lei": "549300KMFXCNZW2IQ177"},
    {"company": "Siemens Healthineers", "symbol": "SMMNY", "region": "EU", "market": "EU", "market_rank": 72, "country": "DE", "industry": "Health Care", "lei": "529900QBVWXMWANH7H45"},
    {"company": "Skandinaviska Enskilda Banken", "symbol": "SVKEF", "region": "EU", "market": "EU", "market_rank": 73, "country": "SE", "industry": "Financials", "lei": "636700UHHSMBFP1ZB424"},
    {"company": "ASM International", "symbol": "ASMIY", "region": "EU", "market": "EU", "market_rank": 74, "country": "NL", "industry": "Information Technology", "lei": "7245001I22ND6ZFHX623"},
    {"company": "Danske Bank", "symbol": "DNKEY", "region": "EU", "market": "EU", "market_rank": 75, "country": "DK", "industry": "Financials", "lei": "MAES062Z21O4RZ2U7M96"},
    {"company": "Ferrovial", "symbol": "FER", "region": "EU", "market": "EU", "market_rank": 76, "country": "NL", "industry": "Industrials", "lei": "72450022R2ZFL41Y6I04", "cik": "0001468522"},
    {"company": "Swedbank", "symbol": "SWDBY", "region": "EU", "market": "EU", "market_rank": 77, "country": "SE", "industry": "Financials", "lei": "5493004K4N3Q8DHT2X73"},
    {"company": "ArcelorMittal", "symbol": "MT", "region": "EU", "market": "EU", "market_rank": 78, "country": "LU", "industry": "Materials", "lei": "RT3QO2NTSFQYP2ETVQ37", "cik": "0001243429"},
    {"company": "Compagnie de Saint Gobain", "symbol": "CODYY", "region": "EU", "market": "EU", "market_rank": 79, "country": "FR", "industry": "Industrials", "lei": "NFONVGN05Z0FMN5PEC35"},
    {"company": "Volkswagen", "symbol": "VWAGY", "region": "EU", "market": "EU", "market_rank": 80, "country": "DE", "industry": "Consumer Discretionary", "lei": "391200SQ3Y7S8Y6CQU11"},
    {"company": "Banca Monte dei Paschi di Siena", "symbol": "BMDPF", "region": "EU", "market": "EU", "market_rank": 81, "country": "IT", "industry": "Financials", "lei": "J4CP7MHCXR8DAQMKIL78", "cik": "0001002788"},
    {"company": "Prysmian SpA", "symbol": "PRYMY", "region": "EU", "market": "EU", "market_rank": 82, "country": "IT", "industry": "Industrials"},
    {"company": "Daimler Truck Holding", "symbol": "DTRUY", "region": "EU", "market": "EU", "market_rank": 83, "country": "DE", "industry": "Industrials", "lei": "529900PW78JIYOUBSR24"},
    {"company": "Assa Abloy", "symbol": "ASAZY", "region": "EU", "market": "EU", "market_rank": 84, "country": "SE", "industry": "Industrials", "lei": "549300LO454LXHC0IN69"},
    {"company": "Universal Music Group", "symbol": "UNVGY", "region": "EU", "market": "EU", "market_rank": 85, "country": "NL", "industry": "Communication Services", "lei": "724500GJBUL3D9TW9Y18", "cik": "0001890126"},
    {"company": "Bayerische Motoren Werke", "symbol": "BAMXF", "region": "EU", "market": "EU", "market_rank": 86, "country": "DE", "industry": "Consumer Discretionary", "lei": "YEH5ZCD6E441RHVHD759", "cik": "0001446250"},
    {"company": "Legrand", "symbol": "LGRDY", "region": "EU", "market": "EU", "market_rank": 87, "country": "FR", "industry": "Industrials", "lei": "969500PKEWDAV28KWS11"},
    {"company": "Asmodee Group", "symbol": "ASMOF", "region": "EU", "market": "EU", "market_rank": 88, "country": "SE", "industry": "Consumer Discretionary", "lei": "636700G5993BBAFDYD02"},
    {"company": "Poste Italiane", "symbol": "PITAF", "region": "EU", "market": "EU", "market_rank": 89, "country": "IT", "industry": "Financials", "lei": "815600358BDF1D861F78"},
    {"company": "EQT", "symbol": "EQBBF", "region": "EU", "market": "EU", "market_rank": 90, "country": "SE", "industry": "Financials", "lei": "5493000OBJ47P5LX5D79"},
    {"company": "Nebius Group", "symbol": "NBIS", "region": "EU", "market": "EU", "market_rank": 91, "country": "NL", "industry": "Information Technology", "lei": "549300GGZHJ5Q1B18P93", "cik": "0001513845"},
    {"company": "STMicroelectronics", "symbol": "STM", "region": "EU", "market": "EU", "market_rank": 92, "country": "NL", "industry": "Information Technology", "lei": "213800Z8NOHIKRI42W10", "cik": "0000932787"},
    {"company": "Medicover", "symbol": "MCVEY", "region": "EU", "market": "EU", "market_rank": 93, "country": "SE", "industry": "Health Care", "lei": "549300073ZZ8GVKW7N65"},
    {"company": "Hochtief", "symbol": "HOCFF", "region": "EU", "market": "EU", "market_rank": 94, "country": "DE", "industry": "Industrials", "lei": "529900BA5V8GXCIBH462"},
    {"company": "Adidas", "symbol": "ADDYY", "region": "EU", "market": "EU", "market_rank": 95, "country": "DE", "industry": "Consumer Discretionary", "lei": "549300JSX0Z4CW0V5023"},
    {"company": "AP Moeller - Maersk", "symbol": "AMKBY", "region": "EU", "market": "EU", "market_rank": 96, "country": "DK", "industry": "Industrials", "lei": "549300D2K6PKKKXVNN73"},
    {"company": "ABN Amro Bank", "symbol": "AAVMY", "region": "EU", "market": "EU", "market_rank": 97, "country": "NL", "industry": "Financials", "lei": "BFXS5XCH7N0Y05NIXW11"},
    {"company": "Hannover Rueck", "symbol": "HVRRY", "region": "EU", "market": "EU", "market_rank": 98, "country": "DE", "industry": "Financials", "lei": "529900KIN5BE45V5KB18"},
    {"company": "Leonardo", "symbol": "FINMY", "region": "EU", "market": "EU", "market_rank": 99, "country": "IT", "industry": "Industrials", "lei": "81560061079BDB86F059"},
    {"company": "Koninklijke Ahold Delhaize", "symbol": "ADRNY", "region": "EU", "market": "EU", "market_rank": 100, "country": "NL", "industry": "Consumer Staples", "lei": "724500C9GNBV20UYRX36"},
)



def top_us_uk_eu_companies() -> list[dict]:
    """Return fresh mappings so callers cannot mutate the static universe."""
    return [
        dict(company)
        for company in (*TOP_US_COMPANIES, *TOP_UK_COMPANIES, *TOP_EU_COMPANIES)
    ]
